# Generated by Django 4.2.5 on 2023-11-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
    ]
