# Generated by Django 4.2.5 on 2023-10-25 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_replymessage_admin_alter_wallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymessage',
            name='admin',
            field=models.ForeignKey(default=(27,), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
