# Generated by Django 4.2.5 on 2023-11-06 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_productreview_user_name_alter_replymessage_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymessage',
            name='admin',
            field=models.ForeignKey(default=(27,), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
