# Generated by Django 4.2.5 on 2023-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_availability_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_area',
            name='image',
            field=models.ImageField(upload_to='media/media/banner_img'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='media/media/slider_img'),
        ),
    ]
