# Generated by Django 4.2.5 on 2023-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_banner_area_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_area',
            name='image',
            field=models.ImageField(upload_to='banner_img'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_img'),
        ),
    ]
