# Generated by Django 4.2.5 on 2023-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='media/product_imgs'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image_url',
            field=models.ImageField(upload_to='media/product_imgs'),
        ),
    ]
