# Generated by Django 4.2.5 on 2023-09-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_is_deleted_main_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
