# Generated by Django 4.2.5 on 2023-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_coupon_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default='2023-10-12'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
