# Generated by Django 4.2.5 on 2023-10-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_offers_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
    ]
