# Generated by Django 4.2.5 on 2023-10-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_offer_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
