# Generated by Django 4.2.5 on 2023-10-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offers',
        ),
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.offer')),
            ],
            options={
                'unique_together': {('category', 'offer')},
            },
        ),
    ]
