# Generated by Django 4.2.5 on 2023-10-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_category_offers_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='categories', through='store.OfferCategory', to='store.offer'),
        ),
    ]
